---
- hosts: all
  become: yes
  tasks:
  - name : install git
    apt:
     name: git
     state: present

  - name: install git on nodes
    apt:
     name: tree
     state: present

  - name: install git on nodes
    apt:
     name: wget
     state: present
